language: java
jdk: openjdk8
addons:
  ssh_known_hosts: 101.71.157.173:40022
script:
  - ./mvnw clean package -B
  #- scp -P40022 $TRAVIS_BUILD_DIR/*.jar root@101.71.157.173:/root/apps/
before_install:
  - openssl aes-256-cbc -K $encrypted_bd500e817882_key -iv $encrypted_bd500e817882_iv
    -in id_rsa_travis.enc -out ~/.ssh/id_rsa_travis -d
  - chmod 600 ~/.ssh/id_rsa_travis
  - echo -e "Host 101.71.157.173\n\tIdentityFile ~/.ssh/id_rsa_travis\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config


after_success:
#- ssh root@101.71.157.173 -p 40022 'echo \'script suceeded!\''
  - for name in $(find $TRAVIS_BUILD_DIR -name '*.jar'); do ls -hl $name;  done