server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://${db_host:localhost}:${db_port:3306}/hospital?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&verifyServerCertificate=false&autoReconnct=true&autoReconnectForPools=true&allowMultiQueries=true
    username: root
    password: F*f6e*hS
    driver-class-name: com.mysql.cj.jdbc.Driver