server:
  port: 8088

#spring:
#  datasource:
#    url: jdbc.mysql://localhost:3306/hospital?characterEncoding=utf8&characterSetResults=utf8
#    username:
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver